### ISSUE TITLE
Unknown version source: vcs

### ISSUE THREAD

**Issue by sandorex** [ofek/hatch-vcs#3]
I am getting an error using this plugin
```
PS F:\Workspace\abacus-icalc> hatch version           
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sandorex\.local\bin\hatch.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\hatch\cli\__init__.py", line 202, in main
    return hatch(windows_expand_args=False)
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\click\decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\hatch\cli\version\__init__.py", line 16, in version
    source = app.project.config.version.source
  File "C:\Users\Sandorex\.local\pipx\venvs\hatch\lib\site-packages\hatch\project\config.py", line 416, in source
    raise ValueError(f'Unknown version source: {self.source_name}')
ValueError: Unknown version source: vcs
```

My hatch.toml:
```toml
path = "abacus/__init__.py"

[version]
source = "vcs"
fallback-version = '0.0.0'

[build.hooks.vcs]
version-file = "abacus/__info__.py"
template = """\
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = {version!r}
__version_info__ = {version_tuple!r}
"""
```

**Comment by ofek** [comment]
Thanks, I will fix! For now you can install `hatch-vcs` alongside `hatch`

**Comment by sandorex** [comment]
> Thanks, I will fix! For now you can install `hatch-vcs` alongside `hatch`

Thanks that worked!

**Comment by ofek** [comment]
Fixed in https://github.com/ofek/hatch/releases/tag/hatch-v1.0.0
