### ISSUE TITLE
Package installation by tox fails (specifically, installation from source distribution fails)

### ISSUE THREAD

**Issue by Midnighter** [ofek/hatch-vcs#35]
I have created a minimal project to recreate this issue.

```text
.
├── pyproject.toml
├── src
│   └── dummy
│       └── __init__.py
└── tox.ini
```

`pyproject.toml` contains:
```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[project]
name = "dummy"
requires-python = ">=3.8"
dynamic = ["version"]

[tool.hatch.build]
packages = ["src/dummy"]

[tool.hatch.build.hooks.vcs]
version-file = "src/dummy/_version.py"

[tool.hatch.version]
source = "vcs"
```

`tox.ini` contains:
```ini
[testenv:hello]
allowlist_externals =
    echo
commands=
    echo "Hello World"
```

The `__init__.py` is empty.

Create this project structure, initialize git, and make a commit.

Both `hatch build` and `python -I -m pip install .`  work perfectly fine. Sample output:

```text
Processing /tmp/hatchtox
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dummy
  Building wheel for dummy (pyproject.toml) ... done
  Created wheel for dummy: filename=dummy-0.1.dev1+g110f633.d20230227-py3-none-any.whl size=1348 sha256=fa770dca427f5d32fa2d450fb850d3c362d3856d77f4232e37ab1a9ec6ecd14f
  Stored in directory: /tmp/pip-ephem-wheel-cache-78pmptuk/wheels/ee/f2/56/3bb9279028ba34018b8936e3a9b0b317348e74849e335fff0d
Successfully built dummy
Installing collected packages: dummy
  Attempting uninstall: dummy
    Found existing installation: dummy 0.1.dev1+g110f633.d20230227
    Uninstalling dummy-0.1.dev1+g110f633.d20230227:
      Successfully uninstalled dummy-0.1.dev1+g110f633.d20230227
Successfully installed dummy-0.1.dev1+g110f633.d20230227
```

Unfortunately, `tox` fails to install the package. Tox is my favorite way to configure tests so it would be a pity not to be able to use both hatch-vcs and tox. Error message:

```text
.pkg: install_requires> python -I -m pip install hatch-vcs hatchling
.pkg: _optional_hooks> python /home/moritz/.pyenv/versions/3.10.8/envs/hatch/lib/python3.10/site-packages/pyproject_api/_backend.py True hatchling.build
.pkg: get_requires_for_build_sdist> python /home/moritz/.pyenv/versions/3.10.8/envs/hatch/lib/python3.10/site-packages/pyproject_api/_backend.py True hatchling.build
.pkg: build_sdist> python /home/moritz/.pyenv/versions/3.10.8/envs/hatch/lib/python3.10/site-packages/pyproject_api/_backend.py True hatchling.build
py: install_package> python -I -m pip install --force-reinstall --no-deps /tmp/hatchtox/.tox/.tmp/package/1/dummy-0.1.dev1+g110f633.d20230227.tar.gz
Processing ./.tox/.tmp/package/1/dummy-0.1.dev1+g110f633.d20230227.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error

  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/tmp/hatchtox/.tox/py/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/tmp/hatchtox/.tox/py/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/tmp/hatchtox/.tox/py/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/tmp/hatchtox/.tox/py/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-o057kqzc/overlay/lib/python3.10/site-packages/hatchling/build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "/tmp/pip-build-env-o057kqzc/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 150, in build
          build_hook.initialize(version, build_data)
        File "/tmp/pip-build-env-o057kqzc/overlay/lib/python3.10/site-packages/hatch_vcs/build_hook.py", line 43, in initialize
          dump_version(self.root, self.metadata.version, self.config_version_file, template=self.config_template)
        File "/tmp/pip-build-env-o057kqzc/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 77, in dump_version
          with open(target, "w") as fp:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-9eku31h5/src/dummy/_version.py'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
py: exit 1 (3.80 seconds) /tmp/hatchtox> python -I -m pip install --force-reinstall --no-deps /tmp/hatchtox/.tox/.tmp/package/1/dummy-0.1.dev1+g110f633.d20230227.tar.gz pid=245545
.pkg: _exit> python /home/moritz/.pyenv/versions/3.10.8/envs/hatch/lib/python3.10/site-packages/pyproject_api/_backend.py True hatchling.build
  py: FAIL code 1 (6.35 seconds)
  evaluation failed :( (6.49 seconds)
```

So tox fails to install from the source distribution. I tried the same thing and indeed a source archive built by hatch fails to install in the same way.

```shell
python -I -m pip install --force-reinstall dist/dummy-0.1.dev1+g110f633.d20230227.tar.gz
```

```text
Processing ./dist/dummy-0.1.dev1+g110f633.d20230227.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/home/moritz/.pyenv/versions/hatch/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/moritz/.pyenv/versions/hatch/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/moritz/.pyenv/versions/hatch/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-oxbzqrsf/overlay/lib/python3.10/site-packages/hatchling/build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "/tmp/pip-build-env-oxbzqrsf/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 150, in build
          build_hook.initialize(version, build_data)
        File "/tmp/pip-build-env-oxbzqrsf/overlay/lib/python3.10/site-packages/hatch_vcs/build_hook.py", line 43, in initialize
          dump_version(self.root, self.metadata.version, self.config_version_file, template=self.config_template)
        File "/tmp/pip-build-env-oxbzqrsf/overlay/lib/python3.10/site-packages/setuptools_scm/__init__.py", line 77, in dump_version
          with open(target, "w") as fp:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-yxu0ny_g/src/dummy/_version.py'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

When I look at the tar archive with `tar -tzf dist/dummy-0.1.dev1+g110f633.d20230227.tar.gz` it contains the version file but the package no longer sits in `src` so that's most likely where the error occurs.

```text
dummy-0.1.dev1+g110f633.d20230227/dummy/__init__.py
dummy-0.1.dev1+g110f633.d20230227/dummy/_version.py
dummy-0.1.dev1+g110f633.d20230227/pyproject.toml
dummy-0.1.dev1+g110f633.d20230227/PKG-INFO
```

Can I somehow change my `pyproject.toml` configuration to account for this?

**Comment by Midnighter** [comment]
When I specify

```toml
[tool.hatch.build.hooks.vcs]
version-file = "_version.py"
```

tox happily installs the package. For both the source distribution and the wheel, the correct version is included in the metadata but obviously there is no longer an importable `_version.py` module. Maybe that's not so bad, though, since it can be accessed via `importlib.metadata`.
