### ISSUE TITLE
Tracebacks on metadata preparation with `setuptools-scm`'s Git archives support

### ISSUE THREAD

**Issue by webknjaz** [ofek/hatch-vcs#80]
I followed this project's README and https://setuptools-scm.readthedocs.io/en/latest/usage/#git-archives in addition to that. I also tried the hack from https://github.com/ofek/hatch-vcs/pull/76/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R69.

Here's what I'm getting
```console
$ git archive --format=tar.gz --output=test-archive.tar.gz HEAD
$ python -Im pip install test-archive.tar.gz
Processing ./test-archive.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      Traceback (most recent call last):
        File "~/src/github/antonbabenko/pre-commit-terraform/some-venv-py313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "~/src/github/antonbabenko/pre-commit-terraform/some-venv-py313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "~/src/github/antonbabenko/pre-commit-terraform/some-venv-py313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
          self.metadata.validate_fields()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/metadata/core.py", line 265, in validate_fields
          _ = self.version
              ^^^^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/metadata/core.py", line 149, in version
          self._version = self._get_version()
                          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/metadata/core.py", line 244, in _get_version
          core_metadata = self.core
                          ^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/metadata/core.py", line 196, in core
          metadata_hook.update(self.core_raw_metadata)
          ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatch_vcs/metadata_hook.py", line 45, in update
          urls[key] = formatter.format(url)
                      ~~~~~~~~~~~~~~~~^^^^^
        File "~/.pyenv/versions/3.13.0rc1/lib/python3.13/string.py", line 190, in format
          return self.vformat(format_string, args, kwargs)
                 ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/utils/context.py", line 143, in vformat
          result, _ = self._vformat(format_string, args, kwargs, used_args, 10)
                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~/.pyenv/versions/3.13.0rc1/lib/python3.13/string.py", line 247, in _vformat
          result.append(self.format_field(obj, format_spec))
                        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatchling/utils/context.py", line 161, in format_field
          return self.__formatters[formatter](value, data)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatch_vcs/metadata_hook.py", line 39, in <lambda>
          'commit_hash': lambda *args: vcs_utils.get_commit_hash(self.root),
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
        File "/tmp/pip-build-env-0ry2in_c/overlay/lib/python3.13/site-packages/hatch_vcs/vcs_utils.py", line 10, in get_commit_hash
          return subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=root).decode('utf-8').strip()
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "~/.pyenv/versions/3.13.0rc1/lib/python3.13/subprocess.py", line 472, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                     **kwargs).stdout
                     ^^^^^^^^^
        File "~/.pyenv/versions/3.13.0rc1/lib/python3.13/subprocess.py", line 577, in run
          raise CalledProcessError(retcode, process.args,
                                   output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by webknjaz** [comment]
Initially, I thought it's #48, but not sure anymore. @RonnyPfannschmidt any clues?

**Comment by RonnyPfannschmidt** [comment]
The full log of the subprocess with debug ebabled is needed

**Comment by webknjaz** [comment]
@RonnyPfannschmidt is that just `-vvvvv` in pip or something else?

**Comment by webknjaz** [comment]
Upon staring at the traceback long enough, I realized that it's hitting this call https://github.com/ofek/hatch-vcs/blob/cefc256/hatch_vcs/metadata_hook.py#L39 in this project's own codebase, not in `setuptools_scm`. And the project is not aware of `.git_archival.txt` so it's calling `git` on a known non-Git directory unconditionally.

This is clearly a bug. Looking more into the names in that module, I think it's related to dynamically templating that URL showcased in README. It makes sense now!

Let me see if dropping that feature from the config will make it skip the call...

Either way, @RonnyPfannschmidt could you label this issue as a bug?

**Comment by webknjaz** [comment]
Just confirmed that this change makes it work:
```diff
  # hatch.toml

  [metadata.hooks.vcs.urls]
- 'Source Archive' = 'https://github.com/antonbabenko/pre-commit-terraform/archive/{commit_hash}.tar.gz'
  'GitHub: repo' = 'https://github.com/antonbabenko/pre-commit-terraform'
```

So when there's no `{commit_hash}` to template, Git is not called.

Note that removing `'urls'` from `dynamic` in `pyproject.toml` does not fix it. So it looks like the rendering is still happening even though, it will be disregarded later. This sounds like another bug to me.
